/*cau 1*/
CREATE TABLE KHACHHANG(MK VARCHAR(10) NOT NULL,TENK NVARCHAR(50),DCHI NVARCHAR(50),SODT VARCHAR(20))

ALTER TABLE KHACHHANG
ADD CONSTRAINT KHOACHINH_KH PRIMARY KEY (MK)

CREATE TABLE BAOCHI(MB VARCHAR(10) NOT NULL,TENBAO NVARCHAR(50),GIA INT)
DROP TABLE BAOCHI

ALTER TABLE BAOCHI
ADD CONSTRAINT KHOACHINH_BC PRIMARY KEY (MB)

CREATE TABLE DATBAO(MK VARCHAR(10) NOT NULL,MB VARCHAR(10) NOT NULL,NGAYDAT DATE,SOLUONG INT)

ALTER TABLE DATBAO
ADD CONSTRAINT KHOACHINH_DB PRIMARY KEY (MK,MB)

/*CAU A*/
SELECT TENK,SUM(SOLUONG*GIA),NGAYDAT AS N'TỔNG TIỀN THEO TỪNG NGÀY' FROM (A JOIN KHACHHANG ON A.MK = KHACHHANG.MK)
GROUP BY NGAYDAT ,TENK

CREATE VIEW A
AS
SELECT MK,GIA ,SOLUONG,NGAYDAT
FROM (BAOCHI JOIN DATBAO ON BAOCHI.MB = DATBAO.MB)

DROP VIEW A


/*cau 2*/
USE QLKH_BAOCHI
CREATE VIEW B 
AS 
SELECT MK, TENBAO, NGAYDAT FROM (BAOCHI JOIN DATBAO ON BAOCHI.MB = DATBAO.MB) WHERE TENBAO = N'NHÂN DÂN'
DROP VIEW B

SELECT TENKH, DIACHI FROM (B JOIN KHACHHANG ON B.MK = KHACHHANG.MK)WHERE YEAR(NGAYDAT) = 2014

/*CAU 3*/

SELECT MK, TENBAO, GIA, SOLUONG, NGAYDAT FROM (DATBAO JOIN BAOCHI ON DATBAO.MB = BAOCHI.MB) WHERE YEAR(NGAYDAT) = 2000

/*CAU 4*/
CREATE VIEW D
AS
SELECT TENBAO, NGAYDAT, SUM(GIA*SOLUONG) AS 'TONGTIEN' FROM (BAOCHI JOIN DATBAO ON BAOCHI.MB = DATBAO.MB)
GROUP BY TENBAO , NGAYDAT
DROP VIEW D

SELECT MAX(TONGTIEN) AS 'MAXMONEY' FROM D