/*cau 2*/
USE QLKH_BAOCHI
CREATE VIEW B 
AS 
SELECT MK, TENBAO, NGAYDAT FROM (BAOCHI JOIN DATBAO ON BAOCHI.MB = DATBAO.MB) WHERE TENBAO = N'NHÂN DÂN'
DROP VIEW B

SELECT TENKH, DIACHI FROM (B JOIN KHACHHANG ON B.MK = KHACHHANG.MK)WHERE YEAR(NGAYDAT) = 2014

/*CAU 3*/

SELECT MK, TENBAO, GIA, SOLUONG, NGAYDAT FROM (DATBAO JOIN BAOCHI ON DATBAO.MB = BAOCHI.MB) WHERE YEAR(NGAYDAT) = 2000

/*CAU 4*/
CREATE VIEW D
AS
SELECT TENBAO, NGAYDAT, SUM(GIA*SOLUONG) AS 'TONGTIEN' FROM (BAOCHI JOIN DATBAO ON BAOCHI.MB = DATBAO.MB)
GROUP BY TENBAO , NGAYDAT
DROP VIEW D

SELECT MAX(TONGTIEN) AS 'MAXMONEY' FROM D